# Generated by Django 5.2.9 on 2026-02-12 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('welcome_text', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('banner_image', models.ImageField(upload_to='event_banners/')),
                ('ticket_template', models.ImageField(upload_to='ticket_templates/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price_until', models.CharField(help_text='до 28 лютого')),
                ('new_price_from', models.CharField(default=' ', help_text='з 1 березня')),
                ('new_price_value', models.DecimalField(decimal_places=2, help_text='нова ціна,її треба вручну поставити в "price"', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('required_group_id', models.BigIntegerField()),
                ('required_group_invite_link', models.CharField(max_length=512)),
                ('announce_chat_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('percentage', models.PositiveIntegerField(default=5)),
                ('is_available', models.BooleanField(default=True)),
                ('valid_until', models.DateTimeField()),
                ('max_uses', models.PositiveIntegerField(default=0)),
                ('uses_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('has_paid_once', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('after_press_pay', 'Після натиснув оплатити'), ('after_payment_success', 'Після успішної оплати'), ('after_join_group', 'Після вступу в групу'), ('after_ticket_sent', 'Після видачі квитка')], max_length=64)),
                ('title', models.CharField(default='Message', max_length=200)),
                ('text', models.TextField()),
                ('delay_seconds', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='core.event')),
            ],
        ),
        migrations.CreateModel(
            name='TgOutboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(db_index=True)),
                ('trigger', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('run_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider', models.CharField(default='monobank', max_length=50)),
                ('provider_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_provider_sync_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.event')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promocode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.tguser')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('image', models.ImageField(upload_to='tickets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tguser')),
            ],
        ),
    ]
