# Generated by Django 5.2.9 on 2026-02-14 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tgbroadcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='new_price_from',
            field=models.CharField(default=' ', help_text='з 1 березня', max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='new_price_value',
            field=models.DecimalField(decimal_places=2, help_text='нова ціна, її треба вручну поставити в "price"', max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='original_price_until',
            field=models.CharField(help_text='до 28 лютого', max_length=64),
        ),
        migrations.AlterField(
            model_name='tgoutboxmessage',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.event'),
        ),
        migrations.AlterField(
            model_name='tgoutboxmessage',
            name='trigger',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='has_paid_once',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
