# Generated by Django 5.2.9 on 2025-12-16 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payment_extra_alter_payment_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='announce_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Message', max_length=200)),
                ('text', models.TextField()),
                ('minutes_before', models.PositiveIntegerField(default=60)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.event')),
            ],
            options={
                'ordering': ('minutes_before', 'id'),
            },
        ),
    ]
