# Generated by Django 5.2.9 on 2026-02-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_event_new_price_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='banner_image',
        ),
    ]
