# Generated by Django 5.2.9 on 2025-12-16 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_announce_chat_id_eventmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('after_press_pay', 'Після натиснув оплатити'), ('after_payment_success', 'Після успішної оплати'), ('after_join_group', 'Після вступу в групу'), ('after_ticket_sent', 'Після видачі квитка')], max_length=64)),
                ('title', models.CharField(default='Message', max_length=200)),
                ('text', models.TextField()),
                ('delay_seconds', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='core.event')),
            ],
        ),
        migrations.CreateModel(
            name='TgOutboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(db_index=True)),
                ('trigger', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('run_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
        ),
        migrations.DeleteModel(
            name='EventMessage',
        ),
    ]
